# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    #run rollup
    - name: Restore dependencies
      working-directory: ./BMinusWebRuntime
      run: dotnet restore
    - name: Publish
      working-directory: ./BMinusWebRuntime
      run: dotnet publish --no-restore -o ${{env.DOTNET_ROOT}}/pub
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with: 
        name: pub
        path: ${{env.DOTNET_ROOT}}/pub

    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: pub
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v3
      
